theme = "native"
icons = "awesome6"

[[block]]
block = "music"
player = "spotify"
max_width = 15
buttons = ["play", "next"]
hide_when_empty = true
[block.format]
full = "{combo}"
short = "{title}"

[[block]]
block = "cpu"
interval = 1
format = "{utilization} {frequency} {boost}"

[[block]]
block = "disk_space"
format = "{icon} {available}"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 20
warning = 30.0
alert = 10.0

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{mem_used_percents}"
format_swap = "{swap_used_percents}"

[[block]]
block = "sound"
driver = "auto"
format = "{volume}"
on_click = "/usr/bin/pavucontrol"

[[block]]
block = "backlight"

[[block]]
block = "battery"
interval = 10
critical = 15
warning = 20
info = 40
good = 60
format = "{percentage:6#100} {percentage} {time}"
device = "BAT1"

[[block]]
block = "networkmanager"
on_click = "kitty --detach nmtui"
interface_name_exclude = ["br\\-[0-9a-f]{12}", "docker\\d+"]
interface_name_include = []
ap_format = "{ssid^10}"
primary_only = true

[[block]]
block = "time"
interval = 1
format = "%a %b %e %R"
on_click = "~/.config/scripts/calendar.sh"
