theme = "native"
icons = "awesome5"

[[block]]
block = "external_ip"
format = "{ip} {country_code}"

[[block]]
block = "time"
interval = 1
format = "%a %b %e %R"
on_click = "~/.config/scripts/calendar.sh"
