theme = "native"
icons = "awesome5"

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{mem_used_percents}"
format_swap = "{swap_used_percents}"

[[block]]
block = "cpu"
interval = 1
format = "{barchart} {utilization} {frequency}"

[[block]]
block = "sound"

[[block]]
block = "backlight"

[[block]]
block = "battery"
interval = 10
format = "{percentage:6#100} {percentage} {time}"

[[block]]
block = "networkmanager"
on_click = "kitty --detach nmtui"
interface_name_exclude = ["br\\-[0-9a-f]{12}", "docker\\d+"]
interface_name_include = []
ap_format = "{ssid^10}"
primary_only = true

[[block]]
block = "time"
interval = 1
format = "%a %d/%m %R"
