[theme]
theme = "native"
[theme.overrides]
separator = " | "
[icons]
icons = "awesome6"

#[[block]]
#block = "focused_window"
#[block.format]
#full = " $title.str(max_w:35,rot_interval:0.5) |"
#short = " $title.str(max_w:15,rot_interval:0.5) |"

[[block]]
block = "music"
player = "spotify"
format = "$icon $combo.str(max_w:25,rot_interval:0.5) $play  $next |"
separator = " - "
seek_step_secs = 0
[[block.click]]
button = "left"
action = "next"
[[block.click]]
button = "left"
action = "play"

[[block]]
block = "cpu"
interval = 1
format = "$utilization $frequency $boost"
[[block.click]]
button = "left"
cmd = "/usr/bin/kitty /usr/bin/btop"

[[block]]
block = "disk_space"
format = "$icon $available"
path = "/"
info_type = "available"
alert_unit = "GB"
interval = 20
warning = 30.0
alert = 10.0
[[block.click]]
button = "left"
cmd = "/usr/bin/baobab"

[[block]]
block = "memory"
format = "$icon $mem_avail.eng(prefix:M)/$mem_total.eng(prefix:M) ($mem_total_used_percents.eng(w:2))"

[[block]]
block = "sound"
driver = "pulseaudio"
device = "hw:1,0"
headphones_indicator = true
format = "$icon {$volume|}"
[[block.click]] 
button = "left"
cmd = "/usr/bin/pavucontrol"

[[block]]
block = "backlight"

[[block]]
block = "battery"
driver = "sysfs"
device = "BAT0"
format = "$icon $percentage"
not_charging_format = "$icon $percentage {$time |}"
interval = 10
critical = 15
warning = 20
info = 40
good = 60

[[block]]
block = "time"
interval = 1
format = " $timestamp.datetime(f:'%a %b %e %R') " 
[[block.click]]
button = "left"
cmd = "~/.config/scripts/calendar.sh"
