[theme]
theme = "native"
[icons]
icons = "awesome6"

[[block]]
block = "time"
interval = 1
format = " $timestamp.datetime(f:'%a %b %e %R') " 
[[block.click]]
button = "left"
cmd = "~/.config/scripts/calendar.sh"
