--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/grey/.wallpaper/background4.jpg"

-- Special
background="#240a05"
foreground="#c8c1c0"
cursor="#c8c1c0"

-- Colors
color0="#240a05"
color1="#b6371c"
color2="#c59506"
color3="#aa870d"
color4="#0896b4"
color5="#565ba9"
color6="#b44d87"
color7="#c8c1c0"
color8="#5a4743"
color9="#b6371c"
color10="#c59506"
color11="#aa870d"
color12="#0896b4"
color13="#565ba9"
color14="#b44d87"
color15="#c8c1c0"
