# Shell variables
# Generated by 'wal'
wallpaper="/home/grey/.wallpaper/background4.jpg"

# Special
background='#240a05'
foreground='#c8c1c0'
cursor='#c8c1c0'

# Colors
color0='#240a05'
color1='#b6371c'
color2='#c59506'
color3='#aa870d'
color4='#0896b4'
color5='#565ba9'
color6='#b44d87'
color7='#c8c1c0'
color8='#5a4743'
color9='#b6371c'
color10='#c59506'
color11='#aa870d'
color12='#0896b4'
color13='#565ba9'
color14='#b44d87'
color15='#c8c1c0'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
